# Generated by Django 4.2 on 2024-08-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_like_users'),
        ('products', '0003_product_view_count'),
    ]

    operations = [
    ]
