# Generated by Django 4.2 on 2024-08-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_hashtag_product_hashtags'),
        ('products', '0004_merge_0003_product_like_users_0003_product_view_count'),
    ]

    operations = [
    ]
