# Generated by Django 4.2 on 2024-08-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_merge_20240823_0955'),
        ('products', '0005_merge_20240823_1958'),
    ]

    operations = [
    ]
